/* Configuration for console_tictactoe generated by Alire */
#ifndef CONSOLE_TICTACTOE_CONFIG_H

   #define CONSOLE_TICTACTOE_CONFIG_H

   #define CRATE_VERSION "0.1.0"
   #define CRATE_NAME "console_tictactoe"

   #define ALIRE_HOST_OS "windows"
   #define ALIRE_HOST_ARCH "x86_64"
   #define ALIRE_HOST_DISTRO "msys2"

   #define BUILD_PROFILE_RELEASE 1
   #define BUILD_PROFILE_VALIDATION 2
   #define BUILD_PROFILE_DEVELOPMENT 3

   #define BUILD_PROFILE  1

#endif
